### PR TITLE
fix cdh6.2 on yarn

### LINKED ISSUE #1511: Container failed to launch when running on CDH 6.2
We had a trial of Analytics-zoo on CDH 6.2. Since CDH 6 removed Spark Standalone mode, we run on yarn-client mode.  But container failed to launch due to "line 16: export: `spark.executorEnv.OMP_NUM_THREADS=1': not a valid identifier". So we run on local mode and work around this issue. 
Container log:
```
2019-07-12 14:33:43 INFO  SignalUtils:57 - Registered signal handler for TERM
2019-07-12 14:33:43 INFO  SignalUtils:57 - Registered signal handler for HUP
2019-07-12 14:33:43 INFO  SignalUtils:57 - Registered signal handler for INT
2019-07-12 14:33:43 INFO  SecurityManager:57 - Changing view acls to: yarn,root
2019-07-12 14:33:43 INFO  SecurityManager:57 - Changing modify acls to: yarn,root
2019-07-12 14:33:43 INFO  SecurityManager:57 - Changing view acls groups to: 
2019-07-12 14:33:43 INFO  SecurityManager:57 - Changing modify acls groups to: 
2019-07-12 14:33:43 INFO  SecurityManager:57 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(yarn, root); groups with view permissions: Set(); users  with modify permissions: Set(yarn, root); groups with modify permissions: Set()
2019-07-12 14:33:43 INFO  ApplicationMaster:57 - ApplicationAttemptId: appattempt_1562909986413_0010_000002
2019-07-12 14:33:44 INFO  RMProxy:133 - Connecting to ResourceManager at bdw-m/192.168.41.100:8030
2019-07-12 14:33:44 INFO  YarnRMClient:57 - Registering the ApplicationMaster
2019-07-12 14:33:44 INFO  TransportClientFactory:272 - Successfully created connection to bdw-m/192.168.41.100:45946 after 57 ms (0 ms spent in bootstraps)
2019-07-12 14:33:44 INFO  ApplicationMaster:57 - Preparing Local resources
2019-07-12 14:33:45 INFO  ApplicationMaster:57 - 
===============================================================================
YARN executor launch context:
  env:
    CLASSPATH -> ..
	spark.executorEnv.KMP_BLOCKTIME -> 0
    MKL_NUM_THREADS -> 1
 ..
	SPARK_YARN_STAGING_DIR -> hdfs://bdw-m:8020/user/root/.sparkStaging/application_1562909986413_0010
    SPARK_USER -> root
    spark.executorEnv.KMP_AFFINITY -> granularity=fine,compact,1,0
    spark.executorEnv.OMP_NUM_THREADS -> 1
    spark.executorEnv.KMP_SETTINGS -> 1
    OPENBLAS_NUM_THREADS -> 1
command:
    LD_LIBRARY_PATH=\"{{HADOOP_COMMON_HOME}}/../../../CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/hadoop/lib/native:$LD_LIBRARY_PATH\" \ 
      {{JAVA_HOME}}/bin/java \ 
      -server \ 
      -Xmx122880m \ 
      -Djava.io.tmpdir={{PWD}}/tmp \ 
      '-Dspark.authenticate=false' \ 
      '-Dspark.network.crypto.enabled=false' \ 
      '-Dspark.driver.port=45946' \ 
      '-Dspark.shuffle.service.port=7337' \ 
      -Dspark.yarn.app.container.log.dir=<LOG_DIR> \ 
      -XX:OnOutOfMemoryError='kill %p' \ 
      org.apache.spark.executor.CoarseGrainedExecutorBackend \ 
      --driver-url \ 
      spark://CoarseGrainedScheduler@bdw-m:45946 \ 
      --executor-id \ 
      <executorId> \ 
      --hostname \ 
      <hostname> \ 
      --cores \ 
      44 \ 
      --app-id \ 
      application_1562909986413_0010 \ 
      --user-class-path \ 
      file:$PWD/__app__.jar \ 
      1><LOG_DIR>/stdout \ 
      2><LOG_DIR>/stderr
resources:
    __spark_conf__ -> resource { scheme: "hdfs" host: "bdw-m" port: 8020 file: "/user/root/.sparkStaging/application_1562909986413_0010/__spark_conf__.zip" } size: 148347 timestamp: 1562913195221 type: ARCHIVE visibility: PRIVATE
===============================================================================
2019-07-12 14:33:45 INFO  Configuration:2662 - resource-types.xml not found
2019-07-12 14:33:45 INFO  ResourceUtils:419 - Unable to find 'resource-types.xml'.
2019-07-12 14:33:45 INFO  YarnAllocator:57 - Will request 1 executor container(s), each with 44 core(s) and 135168 MB memory (including 12288 MB of overhead)
2019-07-12 14:33:45 INFO  YarnAllocator:57 - Submitted 1 unlocalized container requests.
2019-07-12 14:33:45 INFO  ApplicationMaster:57 - Started progress reporter thread with (heartbeat : 3000, initial allocation : 200) intervals
2019-07-12 14:33:46 INFO  YarnAllocator:57 - Launching container container_1562909986413_0010_02_000002 on host bdw-1 for executor with ID 1
2019-07-12 14:33:46 INFO  YarnAllocator:57 - Received 1 containers from YARN, launching executors on 1 of them.
2019-07-12 14:33:49 INFO  YarnAllocator:57 - Completed container container_1562909986413_0010_02_000002 on host: bdw-1 (state: COMPLETE, exit status: 1)
2019-07-12 14:33:49 WARN  YarnAllocator:69 - Container marked as failed: container_1562909986413_0010_02_000002 on host: bdw-1. Exit status: 1. Diagnostics: [2019-07-12 14:33:46.216]Exception from container-launch.
Container id: container_1562909986413_0010_02_000002
Exit code: 1
[2019-07-12 14:33:46.217]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
/mnt/disk5/yarn/nm/usercache/root/appcache/application_1562909986413_0010/container_1562909986413_0010_02_000002/launch_container.sh: line 16: export: `spark.executorEnv.OMP_NUM_THREADS=1': not a valid identifier
[2019-07-12 14:33:46.218]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
/mnt/disk5/yarn/nm/usercache/root/appcache/application_1562909986413_0010/container_1562909986413_0010_02_000002/launch_container.sh: line 16: export: `spark.executorEnv.OMP_NUM_THREADS=1': not a valid identifier
2019-07-12 14:33:52 INFO  YarnAllocator:57 - Will request 1 executor container(s), each with 44 core(s) and 135168 MB memory (including 12288 MB of overhead)
2019-07-12 14:33:52 INFO  YarnAllocator:57 - Submitted 1 unlocalized container requests.
2019-07-12 14:33:53 INFO  YarnAllocator:57 - Launching container container_1562909986413_0010_02_000003 on host bdw-3 for executor with ID 2
2019-07-12 14:33:53 INFO  YarnAllocator:57 - Received 1 containers from YARN, launching executors on 1 of them.
2019-07-12 14:33:56 INFO  YarnAllocator:57 - Completed container container_1562909986413_0010_02_000003 on host: bdw-3 (state: COMPLETE, exit status: 1)
2019-07-12 14:33:56 WARN  YarnAllocator:69 - Container marked as failed: container_1562909986413_0010_02_000003 on host: bdw-3. Exit status: 1. Diagnostics: [2019-07-12 14:33:53.665]Exception from container-launch.
Container id: container_1562909986413_0010_02_000003
Exit code: 1
[2019-07-12 14:33:53.666]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
/mnt/disk1/yarn/nm/usercache/root/appcache/application_1562909986413_0010/container_1562909986413_0010_02_000003/launch_container.sh: line 16: export: `spark.executorEnv.OMP_NUM_THREADS=1': not a valid identifier
[2019-07-12 14:33:53.666]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
/mnt/disk1/yarn/nm/usercache/root/appcache/application_1562909986413_0010/container_1562909986413_0010_02_000003/launch_container.sh: line 16: export: `spark.executorEnv.OMP_NUM_THREADS=1': not a valid identifier
2019-07-12 14:33:59 INFO  YarnAllocator:57 - Will request 1 executor container(s), each with 44 core(s) and 135168 MB memory (including 12288 MB of overhead)
2019-07-12 14:33:59 INFO  YarnAllocator:57 - Submitted 1 unlocalized container requests.
2019-07-12 14:34:00 INFO  YarnAllocator:57 - Launching container container_1562909986413_0010_02_000004 on host bdw-2 for executor with ID 3
2019-07-12 14:34:00 INFO  YarnAllocator:57 - Received 1 containers from YARN, launching executors on 1 of them.
2019-07-12 14:34:03 INFO  YarnAllocator:57 - Completed container container_1562909986413_0010_02_000004 on host: bdw-2 (state: COMPLETE, exit status: 1)
2019-07-12 14:34:03 WARN  YarnAllocator:69 - Container marked as failed: container_1562909986413_0010_02_000004 on host: bdw-2. Exit status: 1. Diagnostics: [2019-07-12 14:34:01.173]Exception from container-launch.
Container id: container_1562909986413_0010_02_000004
Exit code: 1
[2019-07-12 14:34:01.175]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
/mnt/disk5/yarn/nm/usercache/root/appcache/application_1562909986413_0010/container_1562909986413_0010_02_000004/launch_container.sh: line 16: export: `spark.executorEnv.OMP_NUM_THREADS=1': not a valid identifier
[2019-07-12 14:34:01.175]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
/mnt/disk5/yarn/nm/usercache/root/appcache/application_1562909986413_0010/container_1562909986413_0010_02_000004/launch_container.sh: line 16: export: `spark.executorEnv.OMP_NUM_THREADS=1': not a valid identifier
```
Script
```
/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/bin/spark-submit \
 --master yarn \
 --deploy-mode client \
 --num-executors 4 \
 --executor-cores 44 \
 --executor-memory 280G \
 --driver-memory 30G \
 --conf spark.network.timeout=10000000 \
 --driver-class-path /root/zewei/analytics-zoo-jdk8/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.6.0-SNAPSHOT-jar-with-dependencies.jar \
 --class com.intel.analytics.zoo.examples.resnet.TrainImageNet \
 /root/zewei/analytics-zoo-jdk8/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.6.0-SNAPSHOT-jar-with-dependencies.jar \
 --batchSize 176 \
 --nEpochs 3 --learningRate 0.1 --warmupEpoch 5 --maxLr 3.2 \
 --depth 50 --classes 1000 \
 --cache ./models \
 --memoryType DRAM \
 -f  hdfs:///user/root/imagenet-sub
```

### PR DESCRIPTION
**Pull request by qiuxin2012**
fix #1511 

As cdh will convert the spark env to shell script, but we set a illegal name.

Manual test on CDH 6.2.

### CODE REVIEW

File: zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala [hunk 1]
```diff
@@ -234,10 +234,10 @@ object NNContext {
       }
     }
     // Set Spark Conf
-    zooConf.setExecutorEnv("spark.executorEnv.KMP_AFFINITY", kmpAffinity)
```
Comment (qiuxin2012) [inline zoo/src/main/scala/com/intel/analytics/zoo/common/NNContext.scala]: `spark.executorEnv.` is duplicated.
```
 def setExecutorEnv(variable: String, value: String): SparkConf = {
    set("spark.executorEnv." + variable, value)
  }
```

**Comment by qiuxin2012** [comment]
jenkins passed.
