### PR TITLE
Fix Scala WND continuous features

### LINKED ISSUE #2496: WND Scala requires continuous features to be int
https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala#L221

This doesn't make sense. continuous features can be float right?

### PR DESCRIPTION
**Pull request by songhappy**
Fix #2496

### CODE REVIEW

File: zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala [hunk 1]
```diff
@@ -217,8 +216,16 @@ object Utils {
...
     val contTensor = Tensor[Float](contCol).fill(0)
-    (0 to contCol - 1).map(i =>
-      contTensor.setValue(i + 1, r.getAs[Int](columnInfo.continuousCols(i)).toFloat))
+    (0 to contCol - 1).map(i =>{
+      val data= r.getAs[Any](columnInfo.continuousCols(i))
+      val td = data match {
+        case n: Int => n.toFloat
+        case n: Long => n.toFloat
+        case n: Double => n.toFloat
+        case n: Float => n
```
Comment (hkvision) [inline zoo/src/main/scala/com/intel/analytics/zoo/models/recommendation/Utils.scala:225]: other types raise an error?

**Comment by songhappy** [comment]
Failing of PR validation has nothing with this change.
http://10.239.47.210:18888/job/ZOO-PR-Validation-Other/3797/
